### ISSUE TITLE
Clock algorithm goes crazy when theres a lot of ppl connected

### ISSUE THREAD

**Issue by bmentges** [gabrielfalcao/tornadio-chat#1]
Hey !

I was studying tornado and stumbled on this project. It's cool and all and I want to thank you for that.

Now on to the problem I found and that you may fix it:

The algorithm for the clock goes that every connected member sends a message to ask for the time, every second, so they can update their clocks with the servers. The problem is that in server.py lines 28-29, for every message of every member, you iterate on the members list to update their clocks as well.

This does not scale well as everyone broadcasts the time every second to everyone. Thats just it, everything else was fine :D

I know this is just an example but I wished to contribute a little as it helped me in my study.

Thanks Gabriel see ya !
Bruno Carvalho (gcom)

**Comment by bmentges** [comment]
I've changed from:

``` python
    def on_message(self, message):
        n = datetime.now().strftime('%H:%M:%S')
        for p in self.members:
            p.send(n)
```

to

``` python
    def on_message(self, message):
        n = datetime.now().strftime('%H:%M:%S')
        self.send(n)
```

**Comment by gabrielfalcao** [comment]
nice man, cool
